### ISSUE TITLE
Cannot get running initially

### ISSUE THREAD

**Issue by jeprecated** [unmonoqueteclea/voilib#6]
I have tried several times, and I've never gotten it to work.

When I try to run the task "Update channel episodes" I get nothing. So I got into the container and ran `voilib-episodes --update` and this was the error I got:

```
root@606bbf399155:/backend# voilib-episodes --update
2024-10-06 07:04:42,987 updating channels form an background task
2024-10-06 07:04:42,987 adding all the Voilib default channels
2024-10-06 07:04:42,987 get or create channel https://feeds.simplecast.com/5dXzywz5, lang es
2024-10-06 07:04:42,987 get or create channel from url: https://feeds.simplecast.com/5dXzywz5, lang es
Traceback (most recent call last):
  File "/usr/local/bin/voilib-episodes", line 8, in <module>
    sys.exit(main())
  File "/backend/src/voilib/cli/episodes.py", line 72, in main
    asyncio.run(_main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/backend/src/voilib/cli/episodes.py", line 56, in _main
    await collection.add_default_channels()
  File "/backend/src/voilib/collection/crawler.py", line 58, in add_default_channels
    created, _ = await get_or_create_channel(podcast["url"], lang)
  File "/backend/src/voilib/collection/crawler.py", line 37, in get_or_create_channel
    ch = await models.Channel.objects.get_or_none(feed=feed_url)
  File "/usr/local/lib/python3.9/site-packages/ormar/queryset/queryset.py", line 944, in get_or_none
    return await self.get(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ormar/queryset/queryset.py", line 965, in get
    return await self.filter(*args, **kwargs).get()
  File "/usr/local/lib/python3.9/site-packages/ormar/queryset/queryset.py", line 985, in get
    rows = await self.database.fetch_all(expr)
  File "/usr/local/lib/python3.9/site-packages/databases/core.py", line 142, in fetch_all
    return await connection.fetch_all(query, values)
  File "/usr/local/lib/python3.9/site-packages/databases/core.py", line 250, in fetch_all
    return await self._connection.fetch_all(built_query)
  File "/usr/local/lib/python3.9/site-packages/databases/backends/sqlite.py", line 98, in fetch_all
    async with self._connection.execute(query_str, args) as cursor:
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/context.py", line 39, in __aenter__
    self._obj = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 190, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
sqlite3.OperationalError: no such table: channels
```

**Comment by unmonoqueteclea** [comment]
Did you check https://github.com/unmonoqueteclea/voilib/blob/main/infra/readme.md#first-run-tasks?

**Comment by jeprecated** [comment]
I am running it in Docker. I states in that readme:

> ℹ️ In Docker-based installations, Voilib will run migrations automatically from a Docker entrypoint. You can skip this step.

I am using the standard docker-compose: 

<details><summary>docker-compose.yaml</summary>
<p>

```yaml
version: "3.9"
name: voilib
services:
  backend:
    # from building development compose services
    image: docker.io/unmonoqueteclea/voilib-backend:3.2.0
    ports:
      - ${VOILIB_API_PORT:-81}:80
    command: uvicorn src.voilib.main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - /mnt/user/MiscAppData/voilib/:/data
      - /mnt/user/Audio/Podcasts/:/data/local
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - 0.0.0.0/app/version
      interval: 6s
      timeout: 10s
      retries: 50
  frontend:
    # from building development compose services
    image: docker.io/unmonoqueteclea/voilib-ui:0.6.0
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - ${VOILIB_FRONTEND_PORT:-80}:5173
    environment:
      - VITE_API_PORT=${VOILIB_API_PORT:-81}
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - 0.0.0.0:5173
      interval: 6s
      timeout: 10s
      retries: 50
  management:
    image: docker.io/unmonoqueteclea/voilib-backend:3.2.0
    ports:
      - ${VOILIB_MANAGEMENT_PORT:-8501}:8501
    entrypoint: ""
    command: streamlit run src/voilib/management/🏠-Home.py
    volumes:
      - /mnt/user/MiscAppData/voilib/:/data
      - /mnt/user/Audio/Podcasts/:/data/local
  redis:
    image: redis:7.0.4-alpine
    hostname: redis
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 1s
      timeout: 3s
      retries: 30
  worker:
    image: docker.io/unmonoqueteclea/voilib-backend:3.2.0
    depends_on:
      redis:
        condition: service_healthy
    entrypoint: ""
    command: python src/voilib/worker.py
    volumes:
      - ./data/:/data/
  qdrant:
    image: qdrant/qdrant:v1.1.3
    expose:
      - 6333
    volumes:
      - /mnt/user/MiscAppData/voilib/qdrant/:/qdrant/storage
networks: {}

``` 

</p>
</details> 


Though in my debugging I did remote into the backend container and run `alembic upgrade head` yet it made no difference

**Comment by unmonoqueteclea** [comment]
There is an entrypoint configured in the backend Docker image (see `entrypoint.sh`) that should run the migrations.
Maybe you can share here the initial logs generated by the backend container

**Comment by jeprecated** [comment]
Alright I found some time, and I've gotten it running and working 🎉 Though my attempts were not without issues 😅

The main fixes to get it working:
1. Set the volume correctly on worker. I had erroneously left the volume there as `- ./data/:./data/` while changing the rest to `/mnt/user/MiscAppData/voilib:/data/local`
2. Manually run `alembic upgrade head` inside the backend container after creation 
3. Add VITE_API_HOST as an environment variable into the containers, as I am not running it on my localhost but another home server running Unraid. I think it would be good to always define this in the docker-compose files, just to avoid people not knowing it was localhost by default.

<details><summary>Final Docker Compose file</summary>
<p>

version: "3.9"
name: voilib
services:
  backend:
    # from building development compose services
    image: docker.io/unmonoqueteclea/voilib-backend:3.2.0
    ports:
      - ${VOILIB_API_PORT}:80
    command: uvicorn src.voilib.main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - ${DATA_FOLDER}:/data
      - ${LOCAL_FILES_FOLDER}:/data/local
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - 0.0.0.0/app/version
      interval: 6s
      timeout: 10s
      retries: 50
  frontend:
    # from building development compose services
    image: docker.io/unmonoqueteclea/voilib-ui:0.6.0
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - ${VOILIB_FRONTEND_PORT}:5173
    environment:
      - VITE_API_PORT=${VOILIB_API_PORT}
      - VITE_API_HOST=${VITE_API_HOST}
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - 0.0.0.0:5173
      interval: 6s
      timeout: 10s
      retries: 50
  management:
    image: docker.io/unmonoqueteclea/voilib-backend:3.2.0
    ports:
      - ${VOILIB_MANAGEMENT_PORT}:8501
    entrypoint: ""
    command: streamlit run src/voilib/management/🏠-Home.py
    volumes:
      - ${DATA_FOLDER}:/data
      - ${LOCAL_FILES_FOLDER}:/data/local
  #    environment:
  #      - VITE_API_PORT=${VOILIB_API_PORT}
  #      - VITE_API_HOST=${VITE_API_HOST}
  redis:
    image: redis:7.0.4-alpine
    hostname: redis
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 1s
      timeout: 3s
      retries: 30
  worker:
    image: docker.io/unmonoqueteclea/voilib-backend:3.2.0
    depends_on:
      redis:
        condition: service_healthy
    entrypoint: ""
    command: python src/voilib/worker.py
    volumes:
      - ${DATA_FOLDER}:/data
      - ${LOCAL_FILES_FOLDER}:/data/local
  qdrant:
    image: qdrant/qdrant:v1.1.3
    expose:
      - 6333
    volumes:
      - /mnt/user/MiscAppData/voilib/qdrant/:/qdrant/storage
networks: {}
</p>
</details> 

I have no idea if the Management container needs VITE_API_HOST and VITE_API_PORT, but it seems to function without it? 🤔

---

I have some other notes, feature requests, and issues. But I'll post them in their own issues / PRs to keep this issue tidy 👍

**Comment by unmonoqueteclea** [comment]
Thank you very much @ohare93. In the following days, I will review the readme (and maybe the compose file) to avoid other people having the same problems!
